### ISSUE TITLE
Add caching ppdb sysnset data correcly

### ISSUE THREAD

**Issue by AlexKay28** [AlexKay28/zarnitsa#8]
Currentyl, in DataAugmenter NLP badly handled ppdb synset existence check.
this thing must follow the next logic:
1. we do check the existence of ppdb in the library folder  
2. Exit the method if it exists
3. Download synset and unpack it in the library folder 

it should looks like this, but it might have better realisation
```
def _check_synset(self, name):
    """Check synset installed"""
    if name == "ppdb":
        my_file = os.path.join(
            self.__class_local_path, "internal_data", "ppdb-2.0-tldr"
        )  # todo: defined but not used
        if not os.path.exists(my_file):
            wget.download(
                "http://nlpgrid.seas.upenn.edu/PPDB/eng/ppdb-2.0-tldr.gz",
                out=os.path.join(self.__class_local_path, "internal_data/")
            )
            subprocess.run(["gz", my_file])
    else:
        raise KeyError(
            f"Synset {name} is unknown! Load manually or fix the name"
        )
```

**Comment by AlexKay28** [comment]
@joein , do you know how to ask python to load needed data to the library directory on the user's computer? I mean, we should load this synset, in our case, into the zarnitsa package, not the working directory where the method was executed. Shortly speaking, it just should be loaded into the `.local/lib/python3.6/site-packages/zarnitsa/` for example

**Comment by joein** [comment]
At first sight you shouldn’t download third party data this way. Need to look into it more closely and find a better approach

**Comment by joein** [comment]
I think the one way is insert it into package as data files like in [here](https://setuptools.readthedocs.io/en/latest/userguide/datafiles.htmlhttps://setuptools.readthedocs.io/en/latest/userguide/datafiles.html) and retrieve  them via [ResourceManager API](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#resourcemanager-api) of pkg_resources. (Also in this article mentioned that it is a recommended by PyPA way), and the second one is download it lazily and place it somewhere like you do.
But I am not confident about this and I think there is a better approach for this.

**Comment by AlexKay28** [comment]
> I think the one way is to insert it into the package as data files like in [here](https://setuptools.readthedocs.io/en/latest/userguide/datafiles.htmlhttps://setuptools.readthedocs.io/en/latest/userguide/datafiles.html) and retrieve them via [ResourceManager API](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#resourcemanager-api) of pkg_resources. (Also in this article mentioned that it is recommended by PyPA way), and the second one is to download it lazily and place it somewhere as you do.
> But I am not confident about this and I think there is a better approach for this.

The first link is broken =(

I think we can use pathlib library to define the path to the zarnista's source code on the user's computer like [this download_file method](https://github.com/explosion/spaCy/blob/733e8ceea9f691aec8ef2ac7dfcc6e83fd90d47a/spacy/cli/_util.py#L345)
